### ISSUE TITLE
Return type of `Cond` wrong

### ISSUE THREAD

**Issue by timjs** [ssrg-vt/koka_compcert#2]
https://github.com/ssrg-vt/koka_compcert/blob/436fab794900cdc36523199416b2af02edc7d6e6/cfrontend/BeePL_Csyntax.v#L71

Here it should also be a translation of `t`, which is the type of both `e'` and `e''`.

**Comment by swarnpriya** [comment]
Yes, types need to be fixed. I am working on it.
